-- CreateEnum
CREATE TYPE "CandidateRoleTitle" AS ENUM ('AI_ENGINEER', 'ML_ENGINEER', 'PROMPT_ENGINEER', 'DATA_SCIENTIST', 'MLOPS_ENGINEER', 'NLP_ENGINEER', 'COMPUTER_VISION_ENGINEER', 'RESEARCH_ENGINEER', 'DATA_ENGINEER', 'AI_PRODUCT_MANAGER', 'OTHER');

-- AlterTable
ALTER TABLE "CandidateProfile" ADD COLUMN "roleTitle" "CandidateRoleTitle",
ADD COLUMN "roleTitleOther" TEXT;
